---
- name: Testing andrewrothstein.leiningen
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'lein --version'
      ansible.builtin.command: bash -lc 'lein --version'
      changed_when: false
      register: leinengen_test_output
    - name: Output from 'lein --version'
      ansible.builtin.debug:
        msg: '{{ leinengen_test_output.stdout }}'
