---
- name: Installing andrewrothstein.temurin
  ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    temurin_app: jdk
- name: Installing andrewrothstien.bash
  ansible.builtin.include_role:
    name: andrewrothstein.bash
- name: Installing andrewrothstein.openssl
  ansible.builtin.include_role:
    name: andrewrothstein.openssl
- name: Installing andrewrothstein.wget
  ansible.builtin.include_role:
    name: andrewrothstein.wget
- name: Downloading {{ leiningen_url }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ leiningen_url }}'
    dest: '{{ leiningen_exe }}'
    mode: '755'
- name: Initializing with {{ leiningen_exe }}
  become: true
  become_user: root
  ansible.builtin.command: bash -lc {{ leiningen_install_dir }}/lein
  args:
    creates: '{{ lookup("env", "HOME") }}/.lein'
